### ISSUE TITLE
ToDo list

### ISSUE THREAD

**Issue by ghost** [jemxx/autobot#13]
Решил себе для памяти сделать список хотелок, жаль что этого нельзя сделать в своей ветке
- [x] 1. Прикрутить число повторов. Пока идея в еще одной команде в начале текстовика Циклы=число_повторов. И по команде Повторить нарасщивать счетчик и сравнивать его с первоначальным. Актуально для проходов, например, Мудрости под постом. Упрощает текстовик - не надо копи-пастить
- [x] 2. Команда ЖдемПобеду все ж работает не пойми как. Попробовать расширить команду ЖдемКартинку флагом, который не будет стопать если картинка не найдена.  
- [x] 3. Подумать над реализацией НабратьИперенести - сократит лишние действия, если надо выгрузить арму из гены для других атак, пока он переезжает

**Comment by jemxx** [comment]
По первому пункту можно флагом сделать, вместо команды. Что то примерно так /Циклы=число_повторов и в Повторить считать циклы

**Comment by ghost** [comment]
Ну или так. В любом случае полезная будет фича.

**Comment by jemxx** [comment]
Еще маленький момент в файле Команды_Автобота.html описание команды ЖдемКартинку есть, а ссылки на нее нет) Видимо выпилили случайно.

**Comment by ghost** [comment]
блин, нарно это я када добавлял ЖдемПобеду прибил(
щас верну и закину

Там два линка на Сообщение было, поправил и залил в свою ветку

**Comment by Marsik-A** [comment]
я сделал реализацию НабратьИперенести, проверю на элитной армии и выложу тогда.

**Comment by jemxx** [comment]
Справку залил в Wiki. Можно клонировать к себе и удобно будет править

**Comment by ghost** [comment]
Я вижу только как локальную копию сделать. А как правки заливать? Там надо из всех команд набора убрать текст про недостающие числа армии, тк сейчас все посканено от 0 до 3000. И флага Количество нет в описании флагов

**Comment by ghost** [comment]
залил к себе исправленную от ошибок, опечаток  и неточностей версию wiki-справки

**Comment by jemxx** [comment]
Так по идее с вики также работать как и с основным репозиторием. Клонируете в отдельную папку и получаете отдельный репозиторий для вики.

**Comment by ghost** [comment]
в Вики там нет ни клонирования ни ветвления, есть только локально. Я уже вручную все залил в свою Вики

**Comment by jemxx** [comment]
Вообще вам должно быть доступно редактирование в Вики. Такая настройка во всяком случае включена.

**Comment by ghost** [comment]
в вашей Вики? не знаю - не нашел, я уже в своей ветке всю Вики справку перебрал и поправил с учетом актуальных правок.

Upd Вашу Вики я могу только смотреть, править нет. Править могу Вики в своей ветке.

**Comment by jemxx** [comment]
Ладно, придумаем как объединить.

**Comment by ghost** [comment]
Я перескринил всех генералов (кроме автобусов) на сплеше, но все равно криво как-то работает их распознавание( Пока не буду заливать - погоняю еще.
